version: '3'
services:
  order-service:
    image: aarie33/order-service:latest
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    networks:
      - rabbitmq_network

  shipping-service:
    image: aarie33/shipping-service:latest
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    networks:
      - rabbitmq_network

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge