version: '3.8'  # Menggunakan Docker Compose versi 3.8 (versi 2 atau lebih)

services:
  item-db:
    image: mongo:3
    container_name: item-db
    volumes:
      - app-db:/data/db
    networks:
      - app-network
    restart: always

  item-app:
    image: aarie33/item-app:v1
    container_name: item-app
    ports:
      - "81:8080"
    depends_on:
      - item-db
    networks:
      - app-network
    restart: always

volumes:
  app-db:

networks:
  app-network:

