apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-backend
  labels:
    app: karsajobs-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: karsajobs-backend
  template:
    metadata:
      labels:
        app: karsajobs-backend
    spec:
      containers:
      - name: karsajobs-backend
        image: aarie33/karsajobs:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-url

