apiVersion: v1
kind: Service
metadata:
  name: karsajobs-frontend
spec:
  type: NodePort
  selector:
    app: karsajobs-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002

