apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: cm9vdA==
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ=
  mongo-url: bW9uZ29kYjovL3Jvb3Q6cGFzc3dvcmRAbW9uZ28tc2VydmljZToyNzAxNy9rYXJzYWpvYnM=
